EmoGameData = {
  max_gear_level = 20,
  stamina_cap = 60,
  stamina_refill = 200,
  stamina_premium_bonus_cap = 0,
  stamina_for_gasoline = 1,
  max_buy_orders = 20,
  max_sell_orders = 20,
  craftsman_prolong_cost = 0.8,
  leviathan_power_add = 50,
  leviathan_tonnage_add = 25000,
  leviathan_critical_mass_add = 50000,
  leviathan_gear_level_add = 100,
  leviathan_engine_power_mul = 0.2,
  leviathan_min_gear_level = 30,
  leviathan_min_universal_rating = 3000,
  lift_jack_yourself_time = 30,
  lifting_jack_max = 5,
  min_score_for_reward = 40,
  max_loot_count = 3,
  clan_war_drop_probability = 0.05,
  resource_base_reward_portion = 0.8,
  resource_result_reward_portion = 0.2,
  engine_power_max = 4000,
  acceleration_max = 2.5,
  acceleration_min = 0.2,
  debriefing_timeout = 27,
  damage_penetration_reduction = 0,
  damage_penetration_reduction_piercing = 0.2,
  fusion_item_count = 3,
  fusion_collection_count = 10,
  china_money_win_reward = 1,
  halloween_money_win_reward = 1,
  new_year_money_win_reward = 5,
  new_year_money_lose_reward = 1,
  ladder_count_draw_as_lose = false,
  clan_creation_cost = 50000,
  suicide_delay = 5,
  season_unlock_lvl = 5,
  season_medium_unlock_lvl = 10,
  season_hard_unlock_lvl = 5,
  score_to_exp_curvature = 17,
  max_firework_in_cardesign = 1,
  max_active_decor_in_cardesign = 2,
  cumulatively_online_reward_level_require = 5,
  gaijin_2step_reward_premium = 86460,
  gaijin_2step_reward_item = "Decal_shield01:BoundItem",
  PremiumCraftingTimeCoef = {
    1,
    1,
    1,
    1,
    1,
    1
  },
  UserBlueprintCost = {
    0,
    0,
    0,
    0,
    1,
    1,
    2,
    2,
    2,
    3,
    3,
    3,
    3,
    4,
    4,
    4,
    4,
    4,
    5,
    5
  },
  InventoryCapacityCost = {
    {capacity = 200, cost = 0},
    {capacity = 225, cost = 1},
    {capacity = 250, cost = 1},
    {capacity = 275, cost = 2},
    {capacity = 300, cost = 2},
    {capacity = 325, cost = 2},
    {capacity = 350, cost = 3},
    {capacity = 375, cost = 3},
    {capacity = 400, cost = 3},
    {capacity = 425, cost = 3},
    {capacity = 450, cost = 4},
    {capacity = 475, cost = 4},
    {capacity = 500, cost = 4},
    {capacity = 525, cost = 4},
    {capacity = 550, cost = 4},
    {capacity = 575, cost = 5},
    {capacity = 600, cost = 5}
  },
  net_cafe_bonus_exp_coef = 0.1,
  DailyBonusExp = {
    {cap = 40000, coef = 4},
    {cap = 50000, coef = 3},
    {cap = 60000, coef = 2},
    {cap = 70000, coef = 1}
  },
  current_privacy_policy_version = 1,
  current_eula_version = 1
}
